# Generated by Django 5.2.12 on 2026-08-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrapp", "0003_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="college",
            field=models.CharField(
                choices=[
                    ("CCJE", "College of Criminal Justice Education"),
                    ("CTED", "College of Teacher Education"),
                    ("CIT", "College of Industrial Technology"),
                    ("CBA", "College of Business Administration"),
                    ("CAS", "College of Arts and Sciences"),
                    ("CAF", "College of Agriculture and Forestry"),
                ],
                default="CAS",
                max_length=10,
            ),
        ),
    ]
