# Generated by Django 5.2.12 on 2026-08-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qrapp", "0004_student_college"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="course",
            new_name="program",
        ),
    ]
